### ISSUE TITLE
Invalid literal error when running clubcpg-cluster

### ISSUE THREAD

**Issue by DLGisch** [waterlandlab/CluBCpG#16]
Hello,

When I try to run
`clubcpg-cluster -a ../../d/Bismark_hg38/bam/small.bam -o /mnt/f/clubCpG  --bins /mnt/f/clubCpG/CompleteBins.small.bam.chr16.log`

I get the following error:

Only one input bam detected. Running in single-file mode
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/dgisch/anaconda3/envs/clubCpG/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/dgisch/anaconda3/envs/clubCpG/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/dgisch/anaconda3/envs/clubCpG/lib/python3.7/site-packages/clubcpg/ClusterReads.py", line 213, in process_bins
    bin_loc = int(bin_loc)
ValueError: invalid literal for int() with base 10: 'size=100'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dgisch/anaconda3/envs/clubCpG/bin/clubcpg-cluster", line 147, in <module>
    cluster_reads.execute()
  File "/home/dgisch/anaconda3/envs/clubCpG/lib/python3.7/site-packages/clubcpg/ClusterReads.py", line 344, in execute
    results = results.get()
  File "/home/dgisch/anaconda3/envs/clubCpG/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: invalid literal for int() with base 10: 'size=100'

I am running in an Ubuntu inside a Windows Subsystem Linux, with Python 3.7.

Thank you!

**Comment by canthonyscott** [comment]
Hello, it looks like you are passing a .log files to the --bins argument. Can you share the contents of that file?

**Comment by DLGisch** [comment]
The contents of .log file  is

INFO:root:Namespace(bin_size=100, chromosome='chr16', input_bam_A='../../d/Bismark_hg38/bam/small.bam', no_overlap=True, num_processors='5', output_dir='/mnt/f/clubCpG', read1_3=0, read1_5=0, read2_3=0, read2_5=0)
INFO:root:Input file: ../../d/Bismark_hg38/bam/small.bam
INFO:root:Chromosome specified: chr16
INFO:root:Bin size: 100
INFO:root:Number of processors: 5
INFO:root:Fix overlapping reads: True
INFO:root:M bias inputs ignoring the following:
read 1 5': 0bp
read1 3': 0bp
read2 5: 0bp
read2 3': 0bp
INFO:root:Tasks remaining = 903400
INFO:root:Tasks remaining = 903400
INFO:root:Correction attempt at bin chr16_1178200: FAILED
INFO:root:Correction attempt at bin chr16_1186100: FAILED
INFO:root:Correction attempt at bin chr16_1205000: FAILED
INFO:root:Tasks remaining = 903400
INFO:root:Correction attempt at bin chr16_17274100: FAILED
INFO:root:Correction attempt at bin chr16_17295500: FAILED
INFO:root:Correction attempt at bin chr16_17327600: FAILED
INFO:root:Correction attempt at bin chr16_17345900: FAILED
INFO:root:Correction attempt at bin chr16_11979300: FAILED
INFO:root:Tasks remaining = 903400
INFO:root:Tasks remaining = 858230
INFO:root:Correction attempt at bin chr16_2034600: FAILED
INFO:root:Tasks remaining = 813060
INFO:root:Correction attempt at bin chr16_21637100: FAILED
INFO:root:Correction attempt at bin chr16_21955000: FAILED
INFO:root:Tasks remaining = 813060
INFO:root:Tasks remaining = 767890
INFO:root:Tasks remaining = 722720
INFO:root:Tasks remaining = 677550
INFO:root:Tasks remaining = 632380
INFO:root:Tasks remaining = 542040
INFO:root:Correction attempt at bin chr16_50579600: FAILED
INFO:root:Tasks remaining = 451700
INFO:root:Tasks remaining = 451700
INFO:root:Tasks remaining = 451700
INFO:root:Tasks remaining = 361360
INFO:root:Correction attempt at bin chr16_57092500: FAILED
INFO:root:Tasks remaining = 361360
INFO:root:Correction attempt at bin chr16_74408300: FAILED
INFO:root:Correction attempt at bin chr16_74415800: FAILED
INFO:root:Correction attempt at bin chr16_74417600: FAILED
INFO:root:Correction attempt at bin chr16_74420500: FAILED
INFO:root:Tasks remaining = 271020
INFO:root:Correction attempt at bin chr16_69956300: FAILED
INFO:root:Correction attempt at bin chr16_69957200: FAILED

**Comment by canthonyscott** [comment]
Sorry for the late reply. But you appear to be passing the wrong file to the --bins argument. You are passing the log file being generated not the bins file. Please see this section https://clubcpg.readthedocs.io/en/latest/usage.html#calculate-bin-coverage

**Comment by DLGisch** [comment]
Sorry my delay to answer too. 
Thanks, in the example I actually changed the .csv file to .log. I also had a problem because the format of the chromosome name was wrong. I thought it was chr16 and it was actually 16.
Thank you for help me
