### ISSUE TITLE
very large log files

### ISSUE THREAD

**Issue by cjgunase** [waterlandlab/CluBCpG#7]
**Describe the bug**
I am seeing some unusually large logs are being reported when I run GLIA/NEURON data.

**Comment by canthonyscott** [comment]
I have found the offending logging calls and those will be updated in a future relase. For now, a workaround can be to edit the clubcpg-coverage file and edit line 79:

`logging.basicConfig(filename=log_file, level=logging.DEBUG)`

And set the level from logging.DEBUG to logging.INFO or higher (WARNING or higher if you really want to quiet it down). This should suppress the excessive logging.

**Comment by canthonyscott** [comment]
This has been fixed in the dev branch, and will be pulled into the next release
